"""Adjus

Revision ID: 1eb8e822bae1
Revises: cc4fc3c2dcc1
Create Date: 2020-09-20 17:06:09.928380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb8e822bae1'
down_revision = 'cc4fc3c2dcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
