"""Add date

Revision ID: 556a9f693d5c
Revises: 6ba1927b1b93
Create Date: 2020-09-21 11:08:58.203170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556a9f693d5c'
down_revision = '6ba1927b1b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
