"""Add Species

Revision ID: 7521fd7984bb
Revises: a7f2610a9b4a
Create Date: 2020-09-20 02:18:27.181849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7521fd7984bb'
down_revision = 'a7f2610a9b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
