"""add TreeTable

Revision ID: a7f2610a9b4a
Revises: 24a1e479e102
Create Date: 2020-09-19 23:28:19.841681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f2610a9b4a'
down_revision = '24a1e479e102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
