"""Adjust relationship

Revision ID: cf5783fd8087
Revises: 15b85a5ebe23
Create Date: 2020-09-20 16:26:44.062337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5783fd8087'
down_revision = '15b85a5ebe23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
