"""Adjust

Revision ID: ec2720ceeb5e
Revises: 1eb8e822bae1
Create Date: 2020-09-20 17:16:04.576608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2720ceeb5e'
down_revision = '1eb8e822bae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_id'), 'species', ['id'], unique=False)
    op.create_index(op.f('ix_species_name'), 'species', ['name'], unique=True)
    op.create_table('tree_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_group_id'), 'tree_group', ['id'], unique=False)
    op.create_index(op.f('ix_tree_group_name'), 'tree_group', ['name'], unique=True)
    op.create_table('tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('specie', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['tree_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_id'), 'tree', ['id'], unique=False)
    op.create_table('harvest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('date_harvest', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['tree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_id'), 'harvest', ['id'], unique=False)
    op.create_index(op.f('ix_harvest_tree_id'), 'harvest', ['tree_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_harvest_tree_id'), table_name='harvest')
    op.drop_index(op.f('ix_harvest_id'), table_name='harvest')
    op.drop_table('harvest')
    op.drop_index(op.f('ix_tree_id'), table_name='tree')
    op.drop_table('tree')
    op.drop_index(op.f('ix_tree_group_name'), table_name='tree_group')
    op.drop_index(op.f('ix_tree_group_id'), table_name='tree_group')
    op.drop_table('tree_group')
    op.drop_index(op.f('ix_species_name'), table_name='species')
    op.drop_index(op.f('ix_species_id'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
